stages:
  - build
  - publish
  - sonarqube
  - depentancytrack
  - read

variables:
  SONAR_TOKEN: "a39a83e08cd27c6aaaeb3db1e6e3ad2874f0e30d"

build:
  stage: build
  image: gradle:8.3
  script:
    - echo "Building Application"
    #- chmod -R 777 gradlew 
    #- ./gradlew build

publish:
  stage: publish
  script:
    - echo "publish Application"
    #- ./gradlew publish

sonarqube:
  stage: sonarqube
  script:
    - echo "scan Application"
    #- ./gradlew sonarqube

depentancytrack:
  stage: depentancytrack
  script:
    - echo "track Application"
    #- ./gradlew cyclonedxBom

variables:
  NEXUS_URL: "http://192.168.1.30:8081"
  REPO_NAME: "app"
  GROUP_ID: "com.example"
  ARTIFACT_ID: "app"
  VERSION: "1.0.0"

read:
  stage: read
  script:
    - |
      artifactPath="/$REPO_NAME/${GROUP_ID//./}/$ARTIFACT_ID/$VERSION/$ARTIFACT_ID-$VERSION.tar"
      nexusChecksumUrl="$NEXUS_URL/service/rest/v1/components?repository=$REPO_NAME&group=$GROUP_ID&name=$ARTIFACT_ID&version=$VERSION"
      artifactInfo=$(curl -s -u admin:lfadmin "$nexusChecksumUrl")
      checksumValue=$(echo "$artifactInfo" | jq -r '.items[0].assets[0].checksum.sha1')
      echo "{\"buildnumber\": \"$CI_PIPELINE_ID\", \"buildurl\": \"$CI_PIPELINE_URL\", \"group\": \"com.logicfocus\", \"checksum\": \"$checksumValue\", \"artifact\": \"$ARTIFACT_ID\", \"ext\": \"tar\", \"version\": \"$VERSION\"}" > buildData.json
    
  artifacts:
    paths:
      - buildDataStash/
    expire_in: 1 week