stages:
  - build
  - deploy
build:
  stage: build
  image: gradle:8.3
  script:
    - echo "Building Application"
    - gradle build

deploy:
  stage: deploy
  script:
    - echo "Building Application"

