stages:
  - build
  - deploy

variables:
  SONAR_TOKEN: "a39a83e08cd27c6aaaeb3db1e6e3ad2874f0e30d"

build:
  stage: build
  image: gradle:8.3
  script:
    - echo "Building Application"
    - ./gradlew build

publish:
  needs:  
    - build
  stage: deploy
  image: gradle:8.3
  before_script:
    - apt update && apt install curl
  script:
    - echo "Publishing to Nexus"
    - ls -al
    - cd app/build/libs
    - ls

