stages:
  - fetch_checksum
  - build
  - publish
  - sonarqube
  - dependencytrack

variables:
  SONAR_TOKEN: "a39a83e08cd27c6aaaeb3db1e6e3ad2874f0e30d"
  NEXUS_URL: "http://192.168.1.30:8081/repository/app"
  ARTIFACT_NAME: "app"
  ARTIFACT_VERSION: "1.0.0"

fetch_checksum:
  stage: fetch_checksum
  image: curlimages/curl
  script:
    - |
      CHECKSUM=$(curl -s $NEXUS_URL/$ARTIFACT_NAME/$ARTIFACT_VERSION/maven-metadata.xml | grep -oPm1 "(?<=<checksums><sha1>).*(?=</sha1>)")
      echo "Checksum: $CHECKSUM"


build:
  stage: build
  image: gradle:8.3
  script:
    - echo "Building Application"
    #- chmod -R 777 gradlew 
    #- ./gradlew build

publish:
  stage: publish
  script:
    - echo "publish Application"
    #- ./gradlew publish

sonarqube:
  stage: sonarqube
  script:
    - echo "scan Application"
    # - ./gradlew sonarqube

dependencytrack:
  stage: dependencytrack
  script:
    - echo "track Application"
    #- ./gradlew cyclonedxBom
