stages:
  - build
  - deploy
build:
  stage: build
  before_script:
    - export JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64/bin/java"
  script:
    - echo "Building Application"
    - ./gradlew clean build

deploy:
  stage: deploy
  script:
    - echo "Deploying JAR file"
    - cd
    - ls
    - cp /home/gitlab-runner/builds/QvfgTw4o/0/logicfocus2/demo/app/build/libs/app.jar /home/ubuntu
    - ls
