stages:
  - build
  - publish
  - sonarqube
  - depentancytrack
  - build_info
  - read_build_info

variables:
  SONAR_TOKEN: "a39a83e08cd27c6aaaeb3db1e6e3ad2874f0e30d"

build:
  stage: build
  image: gradle:8.3
  script:
    - echo "Building Application"
    #- chmod -R 777 gradlew 
    #- ./gradlew build

publish:
  stage: publish
  script:
    - echo "publish Application"
    #- ./gradlew publish

sonarqube:
  stage: sonarqube
  script:
    - echo "scan Application"
    #- ./gradlew sonarqube

depentancytrack:
  stage: depentancytrack
  script:
    - echo "track Application"
    #- ./gradlew cyclonedxBom

build_info:
  stage: build_info
  script:
    - |
      export NEXUS_URL="http://192.168.1.30:8081"
      export REPO_NAME="app"
      export GROUP_ID="com.example"
      export ARTIFACT_ID="app"
      export VERSION="1.0.0"
      export CHECKSUM=$(curl -s -u "admin:lfadmin" "http://192.168.1.30:8081/service/rest/v1/components?repository=app&maven.groupId=com.example&maven.artifactId=app&maven.baseVersion=1.0.0" | jq -r '.items[0].assets[0].checksum.sha1')


      echo "Checksum: $CHECKSUM"


read_build_info:
  stage: read_build_info
  script:
    - echo "Read and save build info checksum"