stages:
  - build
  - deploy
build:
  stage: build
  image: gradle:8.3
  script:
    - echo "Building Application"
    - gradle build

deploy_dev:
  stage: deploy_dev
  script:
    - ./deploy
build_integration:
  stage: build_integration
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - main
