stages:
  - build
  - publish
  - sonarqube
  - depentancytrack
  - build_info
  - read_build_info

variables:
  SONAR_TOKEN: "a39a83e08cd27c6aaaeb3db1e6e3ad2874f0e30d"

build:
  stage: build
  image: gradle:8.3
  script:
    - echo "Building Application"
    - chmod -R 777 gradlew 
    - ./gradlew build

publish:
  stage: publish
  script:
    - ./gradlew publish

sonarqube:
  stage: sonarqube
  script:
    - ./gradlew sonarqube


depentancytrack:
  stage: depentancytrack
  script:
    - ./gradlew cyclonedxBom

  variables:
    NEXUS_URL: "http://192.168.1.30:8081"
    REPO_NAME: "app"
    GROUP_ID: "com.logicfocus"
    ARTIFACT_ID: "app"
    VERSION: "1.0.1"
    NEXUS_USERNAME: "admin"
    NEXUS_PASSWORD: "lfadmin"
    


build_info:
  stage: build_info
  script:
    - |
      artifactPath="/${REPO_NAME}/${GROUP_ID//./}/${ARTIFACT_ID}/${VERSION}/${ARTIFACT_ID}-${VERSION}.jar"
      nexusChecksumUrl="${NEXUS_URL}/service/rest/v1/components?repository=${REPO_NAME}&group=${GROUP_ID}&name=${ARTIFACT_ID}&version=${VERSION}"
      artifactInfo=$(curl -s -u admin:lfadmin ${nexusChecksumUrl})
      checksumValue=$(echo ${artifactInfo} | jq -r '.items[0].assets[0].checksum.sha1')
      echo '{' > buildData.json
      echo "  \"buildnumber\": \"${CI_PIPELINE_IID}\"," >> buildData.json
      echo "  \"buildurl\": \"${CI_PIPELINE_URL}\"," >> buildData.json
      echo '  "group": "com.logicfocus",' >> buildData.json
      echo "  \"checksum\": \"${checksumValue}\"," >> buildData.json
      echo "  \"artifact\": \"${ARTIFACT_ID}\"," >> buildData.json
      echo '  "ext": "jar",' >> buildData.json
      echo "  \"version\": \"${VERSION}\"" >> buildData.json
      echo '}' >> buildData.json
      cat buildData.json
      echo "Publishing build data to artifact registry..."
      curl -u ${NEXUS_USERNAME}:${NEXUS_PASSWORD} --upload-file buildData.json ${NEXUS_URL}/service/rest/v1/components?repository=${REPO_NAME}
  artifacts:
    paths:
      - buildData.json

read_build_info:
  stage: read_build_info
  script:
    - cat buildData.json
