stages:
  - build
  - deploy

variables:
  SONAR_TOKEN: "a39a83e08cd27c6aaaeb3db1e6e3ad2874f0e30d"

build:
  stage: build
  image: gradle:8.3
  script:
    - echo "Building Application"
    - ./gradlew build

publish:
  needs:  
    - build
  stage: deploy
  image: gradle:8.3
  before_script:
    - apt update && apt install curl
  script:
    - echo "Publishing to Nexus"
    - ls -al
    - curl --header admin:lfadmin --upload-file /home/gitlab-runner/builds/RGEsRsoZ/0/logicfocus2/demo/app/build/libs/app.jar http://192.168.1.30:8081/repository/gitlabcicd/app.jar
