stages:
  - build
  - deploy
build:
  stage: build
  image: gradle:8.3
  script:
    - echo "Building Application"
    - gradle build
    - pwd
    - cwd
  artifacts:
    paths:
    #-  build/libs/*.jar
    - build/libs/*.jar
