stages:
  - build
  
build:
  stage: build
  
  
  script:
    - echo "Building Application"
    - gradle build

test:
  stage: test
  script:
    - echo "Test Stage run successfully!"
    - gradle test
