stages:
  - build
  - deploy
build:
  stage: build
  before_script:
    - export JAVA_HOME="/usr/lib/jvm/java-1.17.0-openjdk-amd64"
  script:
    - echo "Building Application"
    - ./gradlew clean build

deploy:
  stage: deploy
  script:
    - echo "Deploying JAR file"
    - cp build/libs/app.jar /home/ubuntu
    - ls
