stages:
  - build
  - deploy

variables:
  SONAR_TOKEN: "a39a83e08cd27c6aaaeb3db1e6e3ad2874f0e30d"

build:
  stage: build
  image: gradle:8.3
  script:
    - echo "Building Application"
    - ./gradlew build

publish:
  needs:  
    - build
  stage: deploy
  image: gradle:8.3
  script:
    - echo "Publishing to Nexus"
    - curl -v -u admin:lfadmin  -H "Content-Type:multipart/form-data" --data-binary /home/gitlab-runner/builds/RGEsRsoZ/0/logicfocus2/demo/app/build/libs/app.jar -X PUT http://192.168.1.30:8081/repository/gitlabcicd/test/1.0.0/app.jar
