stages:
  - build
  - deploy
build:
  stage: build
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-17-openjdk-amd64"
  script:
    - echo "Building Application"
    - ./gradlew build

deploy:
  stage: deploy
  script:
    - echo "Deploying JAR file"
    - cp /home/gitlab-runner/builds/QvfgTw4o/0/logicfocus2/demo/app/build/libs/app.jar /home/ubuntu
