stages:
  - build
  - deploy
build:
  stage: build
  image: gradle:8.3
  before_script:
    - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
  script:
    - echo "Building Application"
    - gradle build  
