stages:
  - build
  - deploy

variables:
  SONAR_TOKEN: "a39a83e08cd27c6aaaeb3db1e6e3ad2874f0e30d"

build:
  stage: build
  image: gradle:8.3
  script:
    - echo "Building Application"
    - ./gradlew build

publish:
  needs:  
    - build
  stage: deploy
  image: gradle:8.3
  script:
    - echo "Publishing to Nexus"
    - gradlew deploy:deploy-file \
      -Durl=http://192.168.1.30:8081 \
      -DrepositoryId=gitlabcicd \
      -Dfile=/home/gitlab-runner/builds/RGEsRsoZ/0/logicfocus2/demo/app/build/libs/app.jar \
      -DgroupId=logicfocus.com \
      -DartifactId=gitlabcicd \
      -Dversion=1.0.1 \
      -Dpackaging=jar \
      -Duser=admin \
      -Dpassword=lfadmin


sonarqube_scan:
  
  stage: build
  image: gradle:8.3
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-1.11.0-openjdk-amd64"
  script:
    - echo "Running SonarQube analysis"
    - ./gradlew sonarqube -Dsonar.host.url=http://192.168.1.12:9000 -Dsonar.projectKey="gitlabcicd"
